#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimNotify_FlapJackSyrupON

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AnimNotify_FlapJackSyrupON.AnimNotify_FlapJackSyrupON_C
// 0x0000 (0x0038 - 0x0038)
class UAnimNotify_FlapJackSyrupON_C final : public UFortAnimNotifyState_DeferredCustomNotify
{
public:
	bool Received_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, const struct FAnimNotifyEventReference& EventReference) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimNotify_FlapJackSyrupON_C">();
	}
	static class UAnimNotify_FlapJackSyrupON_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimNotify_FlapJackSyrupON_C>();
	}
};
static_assert(alignof(UAnimNotify_FlapJackSyrupON_C) == 0x000008, "Wrong alignment on UAnimNotify_FlapJackSyrupON_C");
static_assert(sizeof(UAnimNotify_FlapJackSyrupON_C) == 0x000038, "Wrong size on UAnimNotify_FlapJackSyrupON_C");

}

