#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_PartModifier_Backpack_OriginPrisoner

#include "Basic.hpp"

#include "B_Athena_PartModifier_Backpack_OriginPrisoner_classes.hpp"
#include "B_Athena_PartModifier_Backpack_OriginPrisoner_parameters.hpp"


namespace SDK
{

// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.ExecuteUbergraph_B_Athena_PartModifier_Backpack_OriginPrisoner
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::ExecuteUbergraph_B_Athena_PartModifier_Backpack_OriginPrisoner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "ExecuteUbergraph_B_Athena_PartModifier_Backpack_OriginPrisoner");

	Params::B_Athena_PartModifier_Backpack_OriginPrisoner_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_OriginPrisoner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.On Stat Changed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             State_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Stat_Value                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::On_Stat_Changed(class FName State_Name, int32 Stat_Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "On Stat Changed");

	Params::B_Athena_PartModifier_Backpack_OriginPrisoner_C_On_Stat_Changed Parms{};

	Parms.State_Name = State_Name;
	Parms.Stat_Value = Stat_Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.OnDamageDealt
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::OnDamageDealt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "OnDamageDealt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.OnDamageReceived
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::OnDamageReceived()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "OnDamageReceived");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.OnPawnAndPartChanged
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::OnPawnAndPartChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "OnPawnAndPartChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.OnStatChanged_912730A34C104E88848D83A669BF62D3
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             StatName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   StatValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::OnStatChanged_912730A34C104E88848D83A669BF62D3(class FName StatName, int32 StatValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "OnStatChanged_912730A34C104E88848D83A669BF62D3");

	Params::B_Athena_PartModifier_Backpack_OriginPrisoner_C_OnStatChanged_912730A34C104E88848D83A669BF62D3 Parms{};

	Parms.StatName = StatName;
	Parms.StatValue = StatValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.OnStatChanged_F72B4E884A322CB03020DAA95F839498
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             StatName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   StatValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::OnStatChanged_F72B4E884A322CB03020DAA95F839498(class FName StatName, int32 StatValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "OnStatChanged_F72B4E884A322CB03020DAA95F839498");

	Params::B_Athena_PartModifier_Backpack_OriginPrisoner_C_OnStatChanged_F72B4E884A322CB03020DAA95F839498 Parms{};

	Parms.StatName = StatName;
	Parms.StatValue = StatValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.PlayDamageReceivedAnim
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::PlayDamageReceivedAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "PlayDamageReceivedAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.PlayKillAnim
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::PlayKillAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "PlayKillAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.SetAndPlaySound
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::SetAndPlaySound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "SetAndPlaySound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.Timeline_0__Stage 1__EventFunc
// (BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::Timeline_0__Stage_1__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "Timeline_0__Stage 1__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.Timeline_0__Stage 2__EventFunc
// (BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::Timeline_0__Stage_2__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "Timeline_0__Stage 2__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_OriginPrisoner.B_Athena_PartModifier_Backpack_OriginPrisoner_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void AB_Athena_PartModifier_Backpack_OriginPrisoner_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_OriginPrisoner_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

