#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AISC_Inv_S20_TheOrigin

#include "Basic.hpp"

#include "BP_AISC_Inv_Tandem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AISC_Inv_S20_TheOrigin.BP_AISC_Inv_S20_TheOrigin_C
// 0x0000 (0x00C8 - 0x00C8)
class UBP_AISC_Inv_S20_TheOrigin_C final : public UBP_AISC_Inv_Tandem_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AISC_Inv_S20_TheOrigin_C">();
	}
	static class UBP_AISC_Inv_S20_TheOrigin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AISC_Inv_S20_TheOrigin_C>();
	}
};
static_assert(alignof(UBP_AISC_Inv_S20_TheOrigin_C) == 0x000008, "Wrong alignment on UBP_AISC_Inv_S20_TheOrigin_C");
static_assert(sizeof(UBP_AISC_Inv_S20_TheOrigin_C) == 0x0000C8, "Wrong size on UBP_AISC_Inv_S20_TheOrigin_C");

}

