#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AISC_GA_JonesyTheFirst

#include "Basic.hpp"

#include "BP_AISC_GA_Tandem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AISC_GA_JonesyTheFirst.BP_AISC_GA_JonesyTheFirst_C
// 0x0000 (0x0070 - 0x0070)
class UBP_AISC_GA_JonesyTheFirst_C final : public UBP_AISC_GA_Tandem_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AISC_GA_JonesyTheFirst_C">();
	}
	static class UBP_AISC_GA_JonesyTheFirst_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AISC_GA_JonesyTheFirst_C>();
	}
};
static_assert(alignof(UBP_AISC_GA_JonesyTheFirst_C) == 0x000008, "Wrong alignment on UBP_AISC_GA_JonesyTheFirst_C");
static_assert(sizeof(UBP_AISC_GA_JonesyTheFirst_C) == 0x000070, "Wrong size on UBP_AISC_GA_JonesyTheFirst_C");

}

