#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AILODSettings_CharacterMovement_All

#include "Basic.hpp"

#include "FortniteAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AILODSettings_CharacterMovement_All.BP_AILODSettings_CharacterMovement_All_C
// 0x0000 (0x0970 - 0x0970)
class UBP_AILODSettings_CharacterMovement_All_C final : public UFortAthenaAILODSettings_CharacterMovement
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AILODSettings_CharacterMovement_All_C">();
	}
	static class UBP_AILODSettings_CharacterMovement_All_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AILODSettings_CharacterMovement_All_C>();
	}
};
static_assert(alignof(UBP_AILODSettings_CharacterMovement_All_C) == 0x000008, "Wrong alignment on UBP_AILODSettings_CharacterMovement_All_C");
static_assert(sizeof(UBP_AILODSettings_CharacterMovement_All_C) == 0x000970, "Wrong size on UBP_AILODSettings_CharacterMovement_All_C");

}

