#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Valet_AudioController_Parent

#include "Basic.hpp"

#include "PhysicsCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "ValetRuntime_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Valet_AudioController_Parent.BP_Valet_AudioController_Parent_C
// 0x02E0 (0x06A0 - 0x03C0)
class ABP_Valet_AudioController_Parent_C : public AFortValetAudioController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USynthComponentMoto*                    SynthComponentMoto;                                // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortCollisionAudioComponent*           CollisionAudio_HitObject;                          // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Horn;                                              // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Engine_OnOff;                                      // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortLayeredAudioComponent*             Engine;                                            // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortCollisionAudioComponent*           CollisionAudio_Suspension;                         // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortCollisionAudioComponent*           CollisionAudio_Body;                               // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Moto_FadeOut_Volume_A91224EC482A9C0F90B4E198803A420B; // 0x0400(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Moto_FadeOut__Direction_A91224EC482A9C0F90B4E198803A420B; // 0x0404(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_405[0x3];                                      // 0x0405(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Moto_FadeOut;                                      // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shift_Up_Alpha_93F8CCBD410A7922FEA656ACD9B2EFFB;   // 0x0410(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Shift_Up__Direction_93F8CCBD410A7922FEA656ACD9B2EFFB; // 0x0414(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_415[0x3];                                      // 0x0415(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Shift_Up;                                          // 0x0418(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<EPhysicalSurface, int32>                 SurfaceToSwitchMap;                                // 0x0420(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TSoftObjectPtr<class USoundWave>              EngineIdleLoopWave;                                // 0x0470(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   EngineIdleWaveParam;                               // 0x0498(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49C[0x4];                                      // 0x049C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundWave>              EngineStartWave;                                   // 0x04A0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   EngineStartWaveParam;                              // 0x04C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CC[0x4];                                      // 0x04CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundWave>              EngineOffWave;                                     // 0x04D0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   EngineOffWaveParam;                                // 0x04F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4FC[0x4];                                      // 0x04FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundWave>              HornWave;                                          // 0x0500(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   HornWaveParam;                                     // 0x0528(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52C[0x4];                                      // 0x052C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             ShiftSoundCue;                                     // 0x0530(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              RPMWobbleRange;                                    // 0x0538(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            ShiftUpCurve;                                      // 0x0548(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              ShiftUpCurveRange;                                 // 0x0550(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              ShiftUpPositiveVarianceMultiplier;                 // 0x0560(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              ShiftUpNegativeVarianceMultiplier;                 // 0x0570(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              ShiftCurveDurationRange;                           // 0x0580(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             ShiftDownSoundCue;                                 // 0x0590(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             WaterEnterSoundCue;                                // 0x0598(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             WaterExitSoundCue;                                 // 0x05A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMotoSynthPreset*                       MotoSynthPreset;                                   // 0x05A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bAssetsLoaded;                                     // 0x05B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5B1[0x7];                                      // 0x05B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             TirePoppedSoundCue;                                // 0x05B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             WindowBreakSoundCue;                               // 0x05C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             DamagedCue;                                        // 0x05C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             PreDestroySoundCue;                                // 0x05D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             DestroySoundCue;                                   // 0x05D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             DestroyedLandSound;                                // 0x05E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bDestroyed;                                        // 0x05E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5E9[0x7];                                      // 0x05E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        DamageAudioComponent;                              // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             DestroyedPassBySound;                              // 0x05F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             BoostSoundCue;                                     // 0x0600(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             BoostEndSoundCue;                                  // 0x0608(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TiresPopped;                                       // 0x0610(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DamageValue;                                       // 0x0614(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DamageStateSmoke;                                  // 0x0618(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bMotoSynthStopped;                                 // 0x0619(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61A[0x6];                                      // 0x061A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             CollisionBodyLightSoundCue;                        // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              HornPitchOffset;                                   // 0x0628(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         EngineonDelay;                                     // 0x0638(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   ReversingWaveParam;                                // 0x063C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bHasReverseAudio;                                  // 0x0640(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_641[0x3];                                      // 0x0641(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ReversingTriggerTime;                              // 0x0644(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class USoundWave>              ReversingWave;                                     // 0x0648(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   TireBoneName;                                      // 0x0670(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bInitialDestroy;                                   // 0x0674(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_675[0x3];                                      // 0x0675(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      Object_Types;                                      // 0x0678(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FTimerHandle                           LaunchOverlapHandle;                               // 0x0688(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        LaunchPassbyAudio;                                 // 0x0690(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           LaunchUpOverlapHandle;                             // 0x0698(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__Engine_K2Node_ComponentBoundEvent_1_OnLayeredAudioComponentOneshot__DelegateSignature(class UAudioComponent* AudioComponent, class FName ParameterName, int32 OneshotIndex);
	struct FVector2D CalculateRPMWobbleRange();
	void CallReversingAudio();
	void Cancel_Tick_Stop_Rampdown();
	void Destroyed_Land_Audio();
	void Destroyed_Launch_Audio();
	void EngineIdleOn();
	void EventReversingAudio();
	void ExecuteUbergraph_BP_Valet_AudioController_Parent(int32 EntryPoint);
	void Get_Tire_Bone_Name(class FName* TireBoneName_0);
	void GetVehicleSurfaceType(int32* Surface_ID);
	void LocalPlayerInVehicleBP(bool* Result);
	void Moto_FadeOut__FinishedFunc();
	void Moto_FadeOut__UpdateFunc();
	void On_Destroyed_Launch();
	void On_Launch_Passby();
	void On_Vehicle_Surface_Changed(EPhysicalSurface SurfaceTypeVehicleIsOn);
	void OnBodyCollision(const struct FVector& HitLocation, const struct FVector& NormalImpulse, bool* FilteredHit, float* Magnitude);
	void OnBoostEnd();
	void OnBoostStart();
	void OnCacheReferences(class AFortDagwoodVehicle* Vehicle);
	void OnCollisionHit(const struct FVector& Impact_Point, class AActor* Actor_Hit);
	void OnDamage(float Damage_Value);
	void OnDestroy();
	void OnDriverStateChanged(bool Enter);
	void OnHandbrake(bool Start);
	void OnHitPlayer(const struct FVector& ImpactPoint);
	void OnHorn();
	void OnLoaded_034A6FEB4ACEA4EE540B238E15993521(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238E1ED77825(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238E201F8882(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238E54ECEE83(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238E616A5320(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238E6A241E24(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238E9E335119(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238EBA52E151(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238ECEA18750(class UObject* Loaded);
	void OnLoaded_034A6FEB4ACEA4EE540B238EEAC03718(class UObject* Loaded);
	void OnPawnEnteredVehicleSeat(const TScriptInterface<class IFortVehicleInterface>& Vehicle, class AFortPawn* PlayerPawn, int32 SeatIndex);
	void OnPawnExitedVehicleSeat(const TScriptInterface<class IFortVehicleInterface>& Vehicle, class AFortPawn* PlayerPawn, int32 SeatIndex);
	void OnShiftCompleted_Event();
	void OnShiftGear_Event(bool UpShift);
	void OnSleepStateChange(bool Awake);
	void OnStopTick();
	void OnSuspensionCollision(bool* FilteredHit, float* Magnitude);
	void OnTick();
	void OnTireModApplied(const struct FTireInfo& AppliedTireMod);
	void OnTirePop(class FName Bone_Name);
	void OnUpdateOverheat(float OverheatValue, float MaxValue, EFortWeaponOverheatState State, bool IsInCooldown);
	void OnUpdateVehicleFade(float Fade_Amount);
	void OnVehicleFadedOut();
	void OnWaterStateChanged(bool Is_Entering_Water);
	void OnWindowBreak(class FName Bone_Name);
	void Range();
	void SetReversingParameter(bool InBool);
	void Shift_Up__FinishedFunc();
	void Shift_Up__UpdateFunc();
	void TurnOnEngineLoops(bool DriverEnter);
	void UserConstructionScript();
	void Vehicle_End_Play();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Valet_AudioController_Parent_C">();
	}
	static class ABP_Valet_AudioController_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Valet_AudioController_Parent_C>();
	}
};
static_assert(alignof(ABP_Valet_AudioController_Parent_C) == 0x000008, "Wrong alignment on ABP_Valet_AudioController_Parent_C");
static_assert(sizeof(ABP_Valet_AudioController_Parent_C) == 0x0006A0, "Wrong size on ABP_Valet_AudioController_Parent_C");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, UberGraphFrame) == 0x0003C0, "Member 'ABP_Valet_AudioController_Parent_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, SynthComponentMoto) == 0x0003C8, "Member 'ABP_Valet_AudioController_Parent_C::SynthComponentMoto' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, CollisionAudio_HitObject) == 0x0003D0, "Member 'ABP_Valet_AudioController_Parent_C::CollisionAudio_HitObject' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Horn) == 0x0003D8, "Member 'ABP_Valet_AudioController_Parent_C::Horn' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Engine_OnOff) == 0x0003E0, "Member 'ABP_Valet_AudioController_Parent_C::Engine_OnOff' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Engine) == 0x0003E8, "Member 'ABP_Valet_AudioController_Parent_C::Engine' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, CollisionAudio_Suspension) == 0x0003F0, "Member 'ABP_Valet_AudioController_Parent_C::CollisionAudio_Suspension' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, CollisionAudio_Body) == 0x0003F8, "Member 'ABP_Valet_AudioController_Parent_C::CollisionAudio_Body' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Moto_FadeOut_Volume_A91224EC482A9C0F90B4E198803A420B) == 0x000400, "Member 'ABP_Valet_AudioController_Parent_C::Moto_FadeOut_Volume_A91224EC482A9C0F90B4E198803A420B' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Moto_FadeOut__Direction_A91224EC482A9C0F90B4E198803A420B) == 0x000404, "Member 'ABP_Valet_AudioController_Parent_C::Moto_FadeOut__Direction_A91224EC482A9C0F90B4E198803A420B' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Moto_FadeOut) == 0x000408, "Member 'ABP_Valet_AudioController_Parent_C::Moto_FadeOut' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Shift_Up_Alpha_93F8CCBD410A7922FEA656ACD9B2EFFB) == 0x000410, "Member 'ABP_Valet_AudioController_Parent_C::Shift_Up_Alpha_93F8CCBD410A7922FEA656ACD9B2EFFB' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Shift_Up__Direction_93F8CCBD410A7922FEA656ACD9B2EFFB) == 0x000414, "Member 'ABP_Valet_AudioController_Parent_C::Shift_Up__Direction_93F8CCBD410A7922FEA656ACD9B2EFFB' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Shift_Up) == 0x000418, "Member 'ABP_Valet_AudioController_Parent_C::Shift_Up' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, SurfaceToSwitchMap) == 0x000420, "Member 'ABP_Valet_AudioController_Parent_C::SurfaceToSwitchMap' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, EngineIdleLoopWave) == 0x000470, "Member 'ABP_Valet_AudioController_Parent_C::EngineIdleLoopWave' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, EngineIdleWaveParam) == 0x000498, "Member 'ABP_Valet_AudioController_Parent_C::EngineIdleWaveParam' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, EngineStartWave) == 0x0004A0, "Member 'ABP_Valet_AudioController_Parent_C::EngineStartWave' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, EngineStartWaveParam) == 0x0004C8, "Member 'ABP_Valet_AudioController_Parent_C::EngineStartWaveParam' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, EngineOffWave) == 0x0004D0, "Member 'ABP_Valet_AudioController_Parent_C::EngineOffWave' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, EngineOffWaveParam) == 0x0004F8, "Member 'ABP_Valet_AudioController_Parent_C::EngineOffWaveParam' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, HornWave) == 0x000500, "Member 'ABP_Valet_AudioController_Parent_C::HornWave' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, HornWaveParam) == 0x000528, "Member 'ABP_Valet_AudioController_Parent_C::HornWaveParam' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ShiftSoundCue) == 0x000530, "Member 'ABP_Valet_AudioController_Parent_C::ShiftSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, RPMWobbleRange) == 0x000538, "Member 'ABP_Valet_AudioController_Parent_C::RPMWobbleRange' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ShiftUpCurve) == 0x000548, "Member 'ABP_Valet_AudioController_Parent_C::ShiftUpCurve' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ShiftUpCurveRange) == 0x000550, "Member 'ABP_Valet_AudioController_Parent_C::ShiftUpCurveRange' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ShiftUpPositiveVarianceMultiplier) == 0x000560, "Member 'ABP_Valet_AudioController_Parent_C::ShiftUpPositiveVarianceMultiplier' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ShiftUpNegativeVarianceMultiplier) == 0x000570, "Member 'ABP_Valet_AudioController_Parent_C::ShiftUpNegativeVarianceMultiplier' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ShiftCurveDurationRange) == 0x000580, "Member 'ABP_Valet_AudioController_Parent_C::ShiftCurveDurationRange' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ShiftDownSoundCue) == 0x000590, "Member 'ABP_Valet_AudioController_Parent_C::ShiftDownSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, WaterEnterSoundCue) == 0x000598, "Member 'ABP_Valet_AudioController_Parent_C::WaterEnterSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, WaterExitSoundCue) == 0x0005A0, "Member 'ABP_Valet_AudioController_Parent_C::WaterExitSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, MotoSynthPreset) == 0x0005A8, "Member 'ABP_Valet_AudioController_Parent_C::MotoSynthPreset' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, bAssetsLoaded) == 0x0005B0, "Member 'ABP_Valet_AudioController_Parent_C::bAssetsLoaded' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, TirePoppedSoundCue) == 0x0005B8, "Member 'ABP_Valet_AudioController_Parent_C::TirePoppedSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, WindowBreakSoundCue) == 0x0005C0, "Member 'ABP_Valet_AudioController_Parent_C::WindowBreakSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, DamagedCue) == 0x0005C8, "Member 'ABP_Valet_AudioController_Parent_C::DamagedCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, PreDestroySoundCue) == 0x0005D0, "Member 'ABP_Valet_AudioController_Parent_C::PreDestroySoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, DestroySoundCue) == 0x0005D8, "Member 'ABP_Valet_AudioController_Parent_C::DestroySoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, DestroyedLandSound) == 0x0005E0, "Member 'ABP_Valet_AudioController_Parent_C::DestroyedLandSound' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, bDestroyed) == 0x0005E8, "Member 'ABP_Valet_AudioController_Parent_C::bDestroyed' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, DamageAudioComponent) == 0x0005F0, "Member 'ABP_Valet_AudioController_Parent_C::DamageAudioComponent' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, DestroyedPassBySound) == 0x0005F8, "Member 'ABP_Valet_AudioController_Parent_C::DestroyedPassBySound' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, BoostSoundCue) == 0x000600, "Member 'ABP_Valet_AudioController_Parent_C::BoostSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, BoostEndSoundCue) == 0x000608, "Member 'ABP_Valet_AudioController_Parent_C::BoostEndSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, TiresPopped) == 0x000610, "Member 'ABP_Valet_AudioController_Parent_C::TiresPopped' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, DamageValue) == 0x000614, "Member 'ABP_Valet_AudioController_Parent_C::DamageValue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, DamageStateSmoke) == 0x000618, "Member 'ABP_Valet_AudioController_Parent_C::DamageStateSmoke' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, bMotoSynthStopped) == 0x000619, "Member 'ABP_Valet_AudioController_Parent_C::bMotoSynthStopped' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, CollisionBodyLightSoundCue) == 0x000620, "Member 'ABP_Valet_AudioController_Parent_C::CollisionBodyLightSoundCue' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, HornPitchOffset) == 0x000628, "Member 'ABP_Valet_AudioController_Parent_C::HornPitchOffset' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, EngineonDelay) == 0x000638, "Member 'ABP_Valet_AudioController_Parent_C::EngineonDelay' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ReversingWaveParam) == 0x00063C, "Member 'ABP_Valet_AudioController_Parent_C::ReversingWaveParam' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, bHasReverseAudio) == 0x000640, "Member 'ABP_Valet_AudioController_Parent_C::bHasReverseAudio' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ReversingTriggerTime) == 0x000644, "Member 'ABP_Valet_AudioController_Parent_C::ReversingTriggerTime' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, ReversingWave) == 0x000648, "Member 'ABP_Valet_AudioController_Parent_C::ReversingWave' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, TireBoneName) == 0x000670, "Member 'ABP_Valet_AudioController_Parent_C::TireBoneName' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, bInitialDestroy) == 0x000674, "Member 'ABP_Valet_AudioController_Parent_C::bInitialDestroy' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, Object_Types) == 0x000678, "Member 'ABP_Valet_AudioController_Parent_C::Object_Types' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, LaunchOverlapHandle) == 0x000688, "Member 'ABP_Valet_AudioController_Parent_C::LaunchOverlapHandle' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, LaunchPassbyAudio) == 0x000690, "Member 'ABP_Valet_AudioController_Parent_C::LaunchPassbyAudio' has a wrong offset!");
static_assert(offsetof(ABP_Valet_AudioController_Parent_C, LaunchUpOverlapHandle) == 0x000698, "Member 'ABP_Valet_AudioController_Parent_C::LaunchUpOverlapHandle' has a wrong offset!");

}

