#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreativeInteraction_PossessProp

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CreativeInteraction_PossessProp.CreativeInteraction_PossessProp_C
// 0x0008 (0x0128 - 0x0120)
class UCreativeInteraction_PossessProp_C final : public UPossessPropInteraction
{
public:
	class AMinigame_PlayerCreated_C*              Minigame;                                          // 0x0120(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void IsPossessingProp(bool* IsProp);
	void GetFortPlayerPawn(class AFortPlayerPawn** Pawn);
	bool CanInteract();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CreativeInteraction_PossessProp_C">();
	}
	static class UCreativeInteraction_PossessProp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeInteraction_PossessProp_C>();
	}
};
static_assert(alignof(UCreativeInteraction_PossessProp_C) == 0x000008, "Wrong alignment on UCreativeInteraction_PossessProp_C");
static_assert(sizeof(UCreativeInteraction_PossessProp_C) == 0x000128, "Wrong size on UCreativeInteraction_PossessProp_C");
static_assert(offsetof(UCreativeInteraction_PossessProp_C, Minigame) == 0x000120, "Member 'UCreativeInteraction_PossessProp_C::Minigame' has a wrong offset!");

}

