#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_TacShield

#include "Basic.hpp"

#include "GA_Athena_TacShield_classes.hpp"
#include "GA_Athena_TacShield_parameters.hpp"


namespace SDK
{

// Function GA_Athena_TacShield.GA_Athena_TacShield_C.Added_52DA3C8B4E9469B4CD5390ABA25AC382
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::Added_52DA3C8B4E9469B4CD5390ABA25AC382()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "Added_52DA3C8B4E9469B4CD5390ABA25AC382");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.Apply Delayed Regen
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::Apply_Delayed_Regen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "Apply Delayed Regen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.ApplyRegenNoDelay
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::ApplyRegenNoDelay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "ApplyRegenNoDelay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.AttemptRegenEffectRemoval
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::AttemptRegenEffectRemoval()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "AttemptRegenEffectRemoval");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.CheckMaxOverShield
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::CheckMaxOverShield()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "CheckMaxOverShield");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.ClearAircraftBinds
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::ClearAircraftBinds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "ClearAircraftBinds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.ExecuteUbergraph_GA_Athena_TacShield
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::ExecuteUbergraph_GA_Athena_TacShield(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "ExecuteUbergraph_GA_Athena_TacShield");

	Params::GA_Athena_TacShield_C_ExecuteUbergraph_GA_Athena_TacShield Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.FailedToActivatePassiveAbility
// (Event, Public, BlueprintEvent)

void UGA_Athena_TacShield_C::FailedToActivatePassiveAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "FailedToActivatePassiveAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.GetAircraftComponent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            TargetPawn                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortControllerComponent_Aircraft*AircraftComponent                                      (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    TargetPawnOrControllerIsValid                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::GetAircraftComponent(class APawn* TargetPawn, class UFortControllerComponent_Aircraft** AircraftComponent, bool* TargetPawnOrControllerIsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "GetAircraftComponent");

	Params::GA_Athena_TacShield_C_GetAircraftComponent Parms{};

	Parms.TargetPawn = TargetPawn;

	UObject::ProcessEvent(Func, &Parms);

	if (AircraftComponent != nullptr)
		*AircraftComponent = Parms.AircraftComponent;

	if (TargetPawnOrControllerIsValid != nullptr)
		*TargetPawnOrControllerIsValid = Parms.TargetPawnOrControllerIsValid;
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.GetValidPawn
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  PawnToCheck_0                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    PassedPawnCast                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::GetValidPawn(class AFortPlayerPawn** PawnToCheck_0, bool* PassedPawnCast)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "GetValidPawn");

	Params::GA_Athena_TacShield_C_GetValidPawn Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PawnToCheck_0 != nullptr)
		*PawnToCheck_0 = Parms.PawnToCheck_0;

	if (PassedPawnCast != nullptr)
		*PassedPawnCast = Parms.PassedPawnCast;
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.HandleAircraftStateChange
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::HandleAircraftStateChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "HandleAircraftStateChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.HandleNormalShieldBreak
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           EffectCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::HandleNormalShieldBreak(class AActor* EffectCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "HandleNormalShieldBreak");

	Params::GA_Athena_TacShield_C_HandleNormalShieldBreak Parms{};

	Parms.EffectCauser = EffectCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.HandleOvershieldBreak
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           EffectCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::HandleOvershieldBreak(class AActor* EffectCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "HandleOvershieldBreak");

	Params::GA_Athena_TacShield_C_HandleOvershieldBreak Parms{};

	Parms.EffectCauser = EffectCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.IsOvershieldFull
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPawn*                        OptionalPawnIn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    OvershieldFull                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::IsOvershieldFull(class AFortPawn* OptionalPawnIn, bool* OvershieldFull)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "IsOvershieldFull");

	Params::GA_Athena_TacShield_C_IsOvershieldFull Parms{};

	Parms.OptionalPawnIn = OptionalPawnIn;

	UObject::ProcessEvent(Func, &Parms);

	if (OvershieldFull != nullptr)
		*OvershieldFull = Parms.OvershieldFull;
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Athena_TacShield_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "K2_OnEndAbility");

	Params::GA_Athena_TacShield_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.OnAnyShieldDamage
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::OnAnyShieldDamage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "OnAnyShieldDamage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.OnCurrentOvershieldChange
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::OnCurrentOvershieldChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "OnCurrentOvershieldChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.OnDamageReceived
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Athena_TacShield_C::OnDamageReceived(const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "OnDamageReceived");

	Params::GA_Athena_TacShield_C_OnDamageReceived Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.OnMutatorListUpdated
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::OnMutatorListUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "OnMutatorListUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.OnOvershieldBreak
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Instigator                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::OnOvershieldBreak(class AActor* Instigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "OnOvershieldBreak");

	Params::GA_Athena_TacShield_C_OnOvershieldBreak Parms{};

	Parms.Instigator = Instigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.OnShieldBreak
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Instigator                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_TacShield_C::OnShieldBreak(class AActor* Instigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "OnShieldBreak");

	Params::GA_Athena_TacShield_C_OnShieldBreak Parms{};

	Parms.Instigator = Instigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.Removed_0E7B2CBC44BC75F6C8BFDEB429622EEF
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::Removed_0E7B2CBC44BC75F6C8BFDEB429622EEF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "Removed_0E7B2CBC44BC75F6C8BFDEB429622EEF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.SendOvershieldBreakCue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::SendOvershieldBreakCue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "SendOvershieldBreakCue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.SetupAircraftBinds
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::SetupAircraftBinds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "SetupAircraftBinds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_TacShield.GA_Athena_TacShield_C.SetupDBNOBinds
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_TacShield_C::SetupDBNOBinds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_TacShield_C", "SetupDBNOBinds");

	UObject::ProcessEvent(Func, nullptr);
}

}

