#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Creative_PossessProp_Server

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Creative_PossessProp_Server.GA_Creative_PossessProp_Server_C
// 0x0008 (0x0B18 - 0x0B10)
class UGA_Creative_PossessProp_Server_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B10(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void K2_ActivateAbility();
	void ExecuteUbergraph_GA_Creative_PossessProp_Server(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Creative_PossessProp_Server_C">();
	}
	static class UGA_Creative_PossessProp_Server_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Creative_PossessProp_Server_C>();
	}
};
static_assert(alignof(UGA_Creative_PossessProp_Server_C) == 0x000008, "Wrong alignment on UGA_Creative_PossessProp_Server_C");
static_assert(sizeof(UGA_Creative_PossessProp_Server_C) == 0x000B18, "Wrong size on UGA_Creative_PossessProp_Server_C");
static_assert(offsetof(UGA_Creative_PossessProp_Server_C, UberGraphFrame) == 0x000B10, "Member 'UGA_Creative_PossessProp_Server_C::UberGraphFrame' has a wrong offset!");

}

