#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Male_Commando_Pizza_Pit_Dyn_AnimBp

#include "Basic.hpp"

#include "Male_Commando_Pizza_Pit_Dyn_AnimBp_classes.hpp"
#include "Male_Commando_Pizza_Pit_Dyn_AnimBp_parameters.hpp"


namespace SDK
{

// Function Male_Commando_Pizza_Pit_Dyn_AnimBp.Male_Commando_Pizza_Pit_Dyn_AnimBp_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UMale_Commando_Pizza_Pit_Dyn_AnimBp_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Male_Commando_Pizza_Pit_Dyn_AnimBp_C", "AnimGraph");

	Params::Male_Commando_Pizza_Pit_Dyn_AnimBp_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function Male_Commando_Pizza_Pit_Dyn_AnimBp.Male_Commando_Pizza_Pit_Dyn_AnimBp_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UMale_Commando_Pizza_Pit_Dyn_AnimBp_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Male_Commando_Pizza_Pit_Dyn_AnimBp_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Male_Commando_Pizza_Pit_Dyn_AnimBp.Male_Commando_Pizza_Pit_Dyn_AnimBp_C.ExecuteUbergraph_Male_Commando_Pizza_Pit_Dyn_AnimBp
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMale_Commando_Pizza_Pit_Dyn_AnimBp_C::ExecuteUbergraph_Male_Commando_Pizza_Pit_Dyn_AnimBp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Male_Commando_Pizza_Pit_Dyn_AnimBp_C", "ExecuteUbergraph_Male_Commando_Pizza_Pit_Dyn_AnimBp");

	Params::Male_Commando_Pizza_Pit_Dyn_AnimBp_C_ExecuteUbergraph_Male_Commando_Pizza_Pit_Dyn_AnimBp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

