#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MountedCannon_Gunner_AnimBP

#include "Basic.hpp"

#include "MountedCannon_Gunner_AnimBP_classes.hpp"
#include "MountedCannon_Gunner_AnimBP_parameters.hpp"


namespace SDK
{

// Function MountedCannon_Gunner_AnimBP.MountedCannon_Gunner_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UMountedCannon_Gunner_AnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MountedCannon_Gunner_AnimBP_C", "AnimGraph");

	Params::MountedCannon_Gunner_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function MountedCannon_Gunner_AnimBP.MountedCannon_Gunner_AnimBP_C.ExecuteUbergraph_MountedCannon_Gunner_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMountedCannon_Gunner_AnimBP_C::ExecuteUbergraph_MountedCannon_Gunner_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MountedCannon_Gunner_AnimBP_C", "ExecuteUbergraph_MountedCannon_Gunner_AnimBP");

	Params::MountedCannon_Gunner_AnimBP_C_ExecuteUbergraph_MountedCannon_Gunner_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

