#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ParallelRuntime

#include "Basic.hpp"

#include "ParallelRuntime_classes.hpp"
#include "ParallelRuntime_parameters.hpp"


namespace SDK
{

// Function ParallelRuntime.FortCameraModifier_WestSausage.RemoveSelfFromCameraManager
// (Final, Native, Protected)

void UFortCameraModifier_WestSausage::RemoveSelfFromCameraManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortCameraModifier_WestSausage", "RemoveSelfFromCameraManager");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ParallelRuntime.FortCameraModifier_WestSausage.CalculateDynamicMultipliers
// (Native, Event, Protected, HasOutParams, BlueprintEvent, Const)
// Parameters:
// float                                   OutFOVBoundsMultiplier                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   OutBoostOffsetMultiplier                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFortCameraModifier_WestSausage::CalculateDynamicMultipliers(float* OutFOVBoundsMultiplier, float* OutBoostOffsetMultiplier) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortCameraModifier_WestSausage", "CalculateDynamicMultipliers");

	Params::FortCameraModifier_WestSausage_CalculateDynamicMultipliers Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutFOVBoundsMultiplier != nullptr)
		*OutFOVBoundsMultiplier = Parms.OutFOVBoundsMultiplier;

	if (OutBoostOffsetMultiplier != nullptr)
		*OutBoostOffsetMultiplier = Parms.OutBoostOffsetMultiplier;
}


// Function ParallelRuntime.FortSwingingLayerAnimInstance.GetAttachVectorInPlayerSpace
// (Final, Native, Public, HasOutParams, HasDefaults)
// Parameters:
// struct FVector                          InPlayerToAttachPoint                                  (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector UFortSwingingLayerAnimInstance::GetAttachVectorInPlayerSpace(const struct FVector& InPlayerToAttachPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortSwingingLayerAnimInstance", "GetAttachVectorInPlayerSpace");

	Params::FortSwingingLayerAnimInstance_GetAttachVectorInPlayerSpace Parms{};

	Parms.InPlayerToAttachPoint = std::move(InPlayerToAttachPoint);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ParallelRuntime.FortSwingingLayerAnimInstance.GetPlayerAnglesFromAttachPoint
// (Final, Native, Public, HasOutParams)
// Parameters:
// float                                   Pitch                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   Roll                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   Yaw                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFortSwingingLayerAnimInstance::GetPlayerAnglesFromAttachPoint(float* Pitch, float* Roll, float* Yaw)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortSwingingLayerAnimInstance", "GetPlayerAnglesFromAttachPoint");

	Params::FortSwingingLayerAnimInstance_GetPlayerAnglesFromAttachPoint Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Pitch != nullptr)
		*Pitch = Parms.Pitch;

	if (Roll != nullptr)
		*Roll = Parms.Roll;

	if (Yaw != nullptr)
		*Yaw = Parms.Yaw;
}

}

