#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pickaxe_Aztec_AnimBlueprint

#include "Basic.hpp"

#include "Pickaxe_Aztec_AnimBlueprint_classes.hpp"
#include "Pickaxe_Aztec_AnimBlueprint_parameters.hpp"


namespace SDK
{

// Function Pickaxe_Aztec_AnimBlueprint.Pickaxe_Aztec_AnimBlueprint_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UPickaxe_Aztec_AnimBlueprint_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Pickaxe_Aztec_AnimBlueprint_C", "AnimGraph");

	Params::Pickaxe_Aztec_AnimBlueprint_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function Pickaxe_Aztec_AnimBlueprint.Pickaxe_Aztec_AnimBlueprint_C.ExecuteUbergraph_Pickaxe_Aztec_AnimBlueprint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPickaxe_Aztec_AnimBlueprint_C::ExecuteUbergraph_Pickaxe_Aztec_AnimBlueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Pickaxe_Aztec_AnimBlueprint_C", "ExecuteUbergraph_Pickaxe_Aztec_AnimBlueprint");

	Params::Pickaxe_Aztec_AnimBlueprint_C_ExecuteUbergraph_Pickaxe_Aztec_AnimBlueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

