#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PinkOatmeal_Base_RiftBubble

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function PinkOatmeal_Base_RiftBubble.PinkOatmeal_Base_RiftBubble_C.UserConstructionScript
// 0x0018 (0x0018 - 0x0000)
struct PinkOatmeal_Base_RiftBubble_C_UserConstructionScript final
{
public:
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0000(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PinkOatmeal_Base_RiftBubble_C_UserConstructionScript) == 0x000008, "Wrong alignment on PinkOatmeal_Base_RiftBubble_C_UserConstructionScript");
static_assert(sizeof(PinkOatmeal_Base_RiftBubble_C_UserConstructionScript) == 0x000018, "Wrong size on PinkOatmeal_Base_RiftBubble_C_UserConstructionScript");
static_assert(offsetof(PinkOatmeal_Base_RiftBubble_C_UserConstructionScript, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000000, "Member 'PinkOatmeal_Base_RiftBubble_C_UserConstructionScript::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");

}

